
#Default difficulty caps at 250
[general]
	#Disable/Enables the whole difficulty scaling of this mod. Requires a mc restart
	"Enable difficulty scaling" = false
	#Time in ticks for which the difficulty shouldnt increase at the beginning. One full minecraft day is 24000 ticks
	#Range: > 0
	"Difficulty Delay" = 0
	#Handles increase in difficulty regarding current difficulty.
	#Format is <minimum current difficulty>-<increase every 2400 ticks>
	#Example ["0-0.01","10-0.1","30-0"]
	#-> So the difficulty increases by 0.01 every 2400 ticks (->0.1 per mc day since a mc day has 24000 ticks) till it reaches a difficulty of 10.
	#Then it increases by 1 per mc day till it reaches 30 and then stops.
	"Difficulty Increase" = ["0-0.1", "250-0"]
	#Wether difficulty should only increase with at least one online players or not
	"Ignore Players" = false
	#If true will increase difficulty by the amount of time skipped. Else will only increase difficulty once.
	"Punish Time Skip" = true
	#Disable/Enable friendly fire for owned pets.
	FriendlyFire = true
	#Blacklist for pet you should't be able to give armor to. Pets from mods, which have custom armor already should be included here (for balancing reasons).
	"Pet Blacklist" = []
	#Treat pet blacklist as whitelist
	"Pet Whitelist" = false
	#Increase difficulty with time
	#Here untill its back as a gamerule
	"Difficulty toggle" = true
	#How the difficulty at a position is calculated. Supported values are: 
	#GLOBAL: Serverwide difficulty value
	#PLAYERMAX: Maximum difficulty of players in a 256 radius around the position
	#PLAYERMEAN: Average difficulty of players in a 256 radius around the position
	#Allowed Values: GLOBAL, PLAYERMAX, PLAYERMEAN
	"Difficulty type" = "GLOBAL"

#Black/Whitelist for various stuff
[list]
	#Entities added here will be blacklisted from their assigned flags. Usage:
	#<entity registry name> or <namespace> followed by any of:
	#[ALL,ATTRIBUTES,ARMOR,HELDITEMS,BLOCKBREAK,USEITEM,LADDER,STEAL,GUARDIAN,PARROT,TARGETVILLAGER,NEUTRALAGGRO,REVERSE].
	#Having no flags is equal to ALL. Use REVERSE to reverse all flags. Some flags do nothing for certain mobs!
	#Examples (without <>):
	#<minecraft:sheep> (equal to minecraft:sheep|ALL) excludes sheeps from all modifications
	#<minecraft:sheep|REVERSE|ATTRIBUTES will> add sheep to attributes modification only
	#<minecraft:sheep|ATTRIBUTES> will add sheep to everything except attributes
	#<minecraft> blacklists all minecraft mobs from everything
	"Entity Configs" = ["easy_npc:allay", "aquaculture:minnow", "gothic:meatbug_tamed", "aquaculture:tambaqui", "humancompanions:knight", "gothic", "gothic:molerat", "gothic:bloodfly", "aquaculture:pink_salmon", "dragonsurvival:princess_entity", "aquaculture:atlantic_herring", "siegemachines:culverin", "siegemachines:ballista", "minecraft:glow_squid", "gothic:scavenger", "netherdepthsupgrade:glowdine", "frozenup:chilloo", "netherdepthsupgrade:eyeball_fish", "cnb:minipad", "aquaculture:catfish", "minecraft:trader_llama", "upgrade_aquatic:goose", "cnb:cactem", "goblintraders:goblin_trader", "easy_npc:zombie_villager", "minecraft:horse", "gothic:warg", "aquaculture:brown_shrooma", "minecraft:polar_bear", "mutantmonsters:mutant_snow_golem", "aquaculture:muskellunge", "upgrade_aquatic:nautilus", "goated:geep", "aquaculture:bayad", "aquaculture:brown_trout", "minecraft:llama", "minecraft:pig", "aquaculture:bluegill", "minecraft:turtle", "aquaculture:red_shrooma", "minecraft:sheep", "aquaculture:atlantic_halibut", "orcz:snotlure", "humancompanions:arbalist", "orcz:invinciblespore", "netherdepthsupgrade:searing_cod", "minecraft:tadpole", "minecraft:goat", "minecraft:dolphin", "upgrade_aquatic:immortal_jellyfish", "gothic:fear_stone", "gothic:meatbug", "minecraft:cod", "aquaculture:gar", "dragonsurvival:shooter", "aquaculture:red_grouper", "netherdepthsupgrade:wither_bonefish", "gothic:lurker", "siegemachines:trebuchet", "galosphere:spectator_vision", "siegemachines:battering_ram", "netherdepthsupgrade:soulsuckeSr", "minecraft:donkey", "humancompanions:axeguard", "upgrade_aquatic:box_jellyfish", "frozenup:penguin", "minecraft:squid", "minecraft:skeleton_horse", "mutantmonsters:spider_pig", "quark:stoneling", "minecraft:cow", "gothic:npc_swamp_camp_hunter", "aquaculture:rainbow_trout", "gothic:molerat_young", "minecraft:bee", "aquaculture:perch", "quark:shiba", "upgrade_aquatic:ululu", "goblintraders:vein_goblin_trader", "galosphere:sparkle", "quark:toretoise", "guardvillagers:guard", "siegemachines:mortar", "minecraft:salmon", "upgrade_aquatic:lionfish", "galosphere:spectre", "aquaculture:jellyfish", "minecraft:snow_golem", "cnb:lizard", "minecraft:mooshroom", "netherdepthsupgrade:fortressgrouper", "minecraft:villager", "aquaculture:tuna", "cnb:little_grebe", "dragonsurvival:prince", "rottencreatures:treasure_chest", "supplementaries:red_merchant", "rottencreatures:hunter_wolf", "minecraft:rabbit", "minecraft:axolotl", "graveyard:nameless_hanged", "galosphere:specterpillar", "aquaculture:piranha", "netherdepthsupgrade:magmacubefish", "aquaculture:box_turtle", "autumnity:snail", "aquaculture:blackfish", "aquaculture:arapaima", "minecraft:strider", "minecraft:parrot", "dragonsurvival:squire", "quark:crab", "easy_npc:skeleton", "siegemachines:catapult", "dragonsurvival:hunter_hound", "minecraft:bat", "minecraft:wandering_trader", "upgrade_aquatic:perch", "aquaculture:carp", "aquaculture:pacific_halibut", "gothic:npc_new_camp_hunter", "minecraft:frog", "minecraft:iron_golem", "netherdepthsupgrade:lava_pufferfish", "netherdepthsupgrade:blazefish", "mutantmonsters:creeper_minion", "aquaculture:pollock", "gothic:dragon_snapper", "gothic:snapper", "autumnity:turkey", "easy_npc:zombie", "cnb:cindershell", "aquaculture:arrau_turtle", "netherdepthsupgrade:bonefish", "aquaculture:boulti", "easy_npc:humanoid_slim", "dragonsurvival:princess", "gothic:razor", "easy_npc:humanoid", "cnb:lilytad", "aquaculture:capitaine", "upgrade_aquatic:cassiopea_jellyfish", "frozenup:reindeer", "upgrade_aquatic:flare", "gothic:gothic_spawn", "minecraft:mule", "orcz:invincibleredspore", "unusualend:bolok", "minecraft:zombie_horse", "gothic:gothic_wolf", "cnb:end_whale", "aquaculture:atlantic_cod", "aquaculture:synodontis", "gothic:npc_oldcamp_hunter", "easy_npc:villager", "minecraft:cat", "minecraft:pufferfish", "aquaculture:starshell_turtle", "cnb:sporeling", "minecraft:fox", "aquaculture:smallmouth_bass", "minecraft:allay", "gothic:ice_wolf", "minecraft:tropical_fish", "graveyard:ghouling", "unusualend:ender_firefly", "netherdepthsupgrade:obsidianfish", "gothic:bloodfly_hornet", "humancompanions:archer", "minecraft:ocelot", "dragonsurvival:knight", "minecraft:chicken", "gothic:npc_farmer", "minecraft:wolf", "easy_npc:fairy", "minecraft:panda", "gothic:scavenger_young", "upgrade_aquatic:pike", "savage_and_ravage"]
	#Any of the following 
	#[ATTRIBUTES, ARMOR, HELDITEMS, BLOCKBREAK, USEITEM, LADDER, STEAL, GUARDIAN, PARROT, TARGETVILLAGER, NEUTRALAGGRO]
	#added here will disable that feature completely.
	#E.g. ["GUARDIAN"] will disable the guardian feature
	"Flag Blacklist" = ["HELDITEMS", "USEITEM", "TARGETVILLAGER", "ATTRIBUTES", "ARMOR", "BLOCKBREAK", "GUARDIAN"]
	#Treat ATTRIBUTES flags as whitelist
	"Attribute Whitelist" = false
	#Treat ARMOR flags as whitelist
	"Armor Equip Whitelist" = false
	#Treat HELDITEMS flags as whitelist
	"Held Equip Whitelist" = false
	#Treat BLOCKBREAK flags as whitelist
	"Breaker Whitelist" = false
	#Treat USEITEM flags as whitelist
	"Item Use Whitelist" = false
	#Treat LADDER flags as whitelist
	"Ladder Whitelist" = false
	#Treat STEAL flags as whitelist
	"Steal Whitelist" = false
	#Treat GUARDIAN flags as whitelist
	"Guardian Whitelist" = false
	#Treat PARROT flags as whitelist
	"Phantom Whitelist" = false
	#Treat TARGETVILLAGER flags as whitelist
	"Villager Whitelist" = false
	#Treat NEUTRALAGGRO flags as whitelist
	"Neutral Aggro Whitelist" = false

#Settings for mod integration
[integration]
	#Should the scaling health mods difficulty system be used instead of this ones. (Requires scaling health mod)
	"Use Scaling Health Mod" = true
	#If true and playerEx is installed will use the level from playerEx as difficulty
	"Use Player EX Mod" = true
	#If true and LevelZ is installed will use the the total skill level from LevelZ as difficulty
	"Use LevelZ Mod" = true

#Settings regarding custom ai for mobs
[ai]
	#Whitelist for blocks, which can be actively broken. 
	#Usage: <registry name;classname;tag;namespace> put "!" infront to exclude blocks
	#Note: If you include common blocks (like grass blocks) the pathfinding can have undesirable results.
	"Block Break Whitelist" = ["forge:glass", "forge:glass_panes", "minecraft:fence_gates", "forge:fence_gates", "minecraft:wooden_doors", "minecraft:cobblestone"]
	#Treat Block Whitelist as Blocklist
	"Breaklist as Blacklist" = false
	#Use the block breaking sound instead of a knocking sound
	Sound = true
	#Chance for a mob to be able to break blocks
	#Range: 0.0 ~ 1.0
	"Breaker Chance" = 0.0
	#Initial cooldown for block breaking mobs
	#Range: > 0
	"Breaker Initial Cooldown" = 120
	#Cooldown for breaking blocks
	#Range: > 0
	"Breaker Cooldown" = 20
	#If mobs should break blocks when not chasing a target
	"Idle Break" = false
	#Chance for a mob to be able to steal items from inventory blocks
	#Range: 0.0 ~ 1.0
	"Stealer Chance" = 0.3
	#Items which will be given to mobs who can break blocks. Empty list = no items. Syntax: id;weight
	#Note: Mobs can only break blocks if the tool they are holding can break the blocks
	"Breaking items" = []
	#Should mobs be able to break block entities? Evaluated before the break list
	"Break BlockEntities" = true
	#Chance for neutral mobs to be aggressive
	#Range: 0.0 ~ 1.0
	"Neutral Aggressive Chance" = 0.1
	#List for of pairs containing which mobs auto target others. Syntax is [mob id]-[mob id] where second value is the target.
	# e.g. minecraft:zombie-minecraft:skeleton makes all zombies target skeletons
	"Auto Target List" = []
	#Difficulty at which mobs are able to break blocks
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Break AI" = 0.0
	#Difficulty at which mobs are able to steal items
	#Range: 0.0 ~ 1.7976931348623157E308
	"Difficulty Steal AI" = 0.0
	#Chance for mobs to be able to summon an aquatic mount
	#Range: 0.0 ~ 1.0
	"Guardian Chance" = 1.0
	#Chance for mobs to be able to summon a flying mount
	#Range: 0.0 ~ 1.0
	"Phantom Chance" = 0.5

#Configs regarding mobs spawning with equipment
[equipment]
	#Blacklist items from whole mods. Add modid to prevent items from that mod being equipped. (For individual items use the equipment.json)
	"Item Blacklist" = []
	#Use blacklist as whitelist
	"Item Whitelist" = true
	#Blacklist for items mobs should never be able to use.
	#Use as in using the item similar to players (e.g. shooting bows)
	"Item Use Blacklist" = ["bigbrain:buckler"]
	#Turn the use blacklist into a whitelist
	"Item Use Whitelist" = false
	#Blacklist for specific mobs and items they shouldnt use (e.g. skeletons already use bows)
	#<entity registry name-item>
	#For different items but same entity use multiple lines
	#Some special names are BOW, TRIDEN, CROSSBOW refering to every bow/trident/crossbow item (So you dont need to type e.g. every bow item)
	"Entity Item Use Blacklist" = ["minecraft:drowned;TRIDENT", "minecraft:illusioner;BOW", "minecraft:piglin;CROSSBOW", "minecraft:pillager;CROSSBOW", "minecraft:skeleton;BOW", "minecraft:snow_golem;minecraft:snowball", "minecraft:stray;BOW", "minecraft:wither_skeleton;BOW"]
	#Base chance that a mob can have one piece of armor
	#Range: 0.0 ~ 1.0
	"Equipment Chance" = 0.1
	#Base chance for each additional armor pieces
	#Range: 0.0 ~ 1.0
	"Additional Equipment Chance" = 0.3
	#Adds additional x*difficulty% to base equip chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Equipment Addition" = 0.3
	#Chance for mobs to have a weapon
	#Range: 0.0 ~ 1.0
	"Weapon Chance" = 0.05
	#Adds additional x*difficulty% to base weapon chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Weapon Chance Add" = 0.3
	#Base chance for each armor pieces to get enchanted
	#Range: 0.0 ~ 1.0
	"Enchanting Chance" = 0.2
	#Adds additional x*difficulty% to base enchanting chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Enchanting Addition" = 0.2
	#Specify min and max enchanting levels according to difficulty. difficulty-minLevel-maxLevel
	"Enchanting Calc" = ["0-5-10", "25-5-15", "50-10-17", "100-15-25", "200-20-30", "250-30-35"]
	#Chance for mobs to have an item in offhand
	#Range: 0.0 ~ 1.0
	"Item Equip Chance" = 0.05
	#Adds additional x*difficulty% to base item chance
	#Range: 0.0 ~ 1.7976931348623157E308
	"Item Chance add" = 0.2
	#Should mobs drop the armor equipped through this mod? Will not change drops if the mob obtained the armor through other means (e.g. vanilla)
	"Should drop equipment" = false

#Settings for attribute modifiers
[attributes]
	#Health will be multiplied by difficulty*0.016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Health Increase Multiplier" = 1.0
	#Health will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Health Increase" = 5.0
	#Round health to the nearest x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Round HP" = 0.5
	#Damage will be multiplied by difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Damage Increase Multiplier" = 1.0
	#Damage will be multiplied by at maximum this. Set to 0 means no limit
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Damage Increase" = 3.0
	#Speed will be increased by difficulty*0.0008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Speed Increase" = 1.0
	#Maximum increase in speed
	#Range: 0.0 ~ 1.0
	"Max Speed" = 0.1
	#Knockback will be increased by difficulty*0.002*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Knockback Increase" = 1.0
	#Maximum increase in knockback
	#Range: 0.0 ~ 1.0
	"Max Knockback" = 0.5
	#Magic resistance will be increased by difficulty*0.0016*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Magic Resistance Increase" = 1.0
	#Maximum increase in magic resistance. Magic reduction is percentage
	#Range: 0.0 ~ 1.0
	"Max Magic Resistance" = 0.4
	#Projectile Damage will be multiplied by 1+difficulty*0.008*x. Set to 0 to disable
	#Range: 0.0 ~ 1.7976931348623157E308
	"Projectile Damage Increase" = 1.0
	#Projectile damage will be multiplied by maximum of this
	#Range: 0.0 ~ 1.7976931348623157E308
	"Max Projectile Damage" = 2.0

